import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <div className="fixed bottom-4 right-4 z-50 flex flex-col items-end space-y-2 group">
          <div className="relative">
           <a href="/"> <img
              src="/logo.png"
              alt="Developer Info"
              className="w-16 h-16 rounded-full border border-white shadow-lg cursor-pointer animate-pulse hover:scale-105 transition-transform duration-200"
            />
            <div className="absolute bottom-full right-0 mb-2 hidden group-hover:block bg-gray-900 text-white text-xs px-3 py-2 rounded shadow-lg whitespace-nowrap">
              Developed by Ketan Chokkara · Internship 2025
            </div></a>
           
          </div>
          <a href="https://github.com/CodeUltr0n" target="_blank" rel="noopener noreferrer">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src="/github.png"
              alt="GitHub"
              className="w-8 h-8 rounded-full border border-white shadow-md hover:scale-110 transition-transform duration-200"
            />
          </a>
          <a href="https://www.linkedin.com/in/ketan-chokkara-2888b2274/" target="_blank" rel="noopener noreferrer">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src="/linkedin.png"
              alt="LinkedIn"
              className="w-8 h-8 rounded-full border border-white shadow-md hover:scale-110 transition-transform duration-200"
            />
          </a>
        </div>
      </body>
    </html>

  );
}
